[package]
name = "recursion_optimization"
version = "0.1.0"
authors = ["Sammy S"]
edition = "2018"

[dependencies]
async-recursion = "0.3.1"
futures = "0.3.5"
fnv = "1.0.7"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "benchmark"
harness = false

[lib]
bench = false
